var hierarchy =
[
    [ "copp::Boundary2", "structcopp_1_1_boundary2.html", null ],
    [ "copp::Boundary3", "structcopp_1_1_boundary3.html", null ],
    [ "copp::Constraints", "classcopp_1_1_constraints.html", null ],
    [ "copp::ConstraintsRef", "classcopp_1_1_constraints_ref.html", null ],
    [ "copp::ErrorInfo", "structcopp_1_1_error_info.html", null ],
    [ "copp::Expected&lt; T &gt;", "classcopp_1_1_expected.html", null ],
    [ "copp::IndexInterval", "structcopp_1_1_index_interval.html", null ],
    [ "copp::Jet3", "structcopp_1_1_jet3.html", null ],
    [ "copp::clarabel::LinearSolverInfo", "structcopp_1_1clarabel_1_1_linear_solver_info.html", null ],
    [ "copp::Matrix", "classcopp_1_1_matrix.html", null ],
    [ "copp::MatrixRef", "classcopp_1_1_matrix_ref.html", null ],
    [ "copp::MatrixView", "classcopp_1_1_matrix_view.html", null ],
    [ "copp::clarabel::detail::NoInitTag", "structcopp_1_1clarabel_1_1detail_1_1_no_init_tag.html", null ],
    [ "copp::NoThrowTag", "structcopp_1_1_no_throw_tag.html", null ],
    [ "copp::Objective", "classcopp_1_1_objective.html", null ],
    [ "copp::clarabel::Options", "structcopp_1_1clarabel_1_1_options.html", null ],
    [ "copp::solver::topp2_ra::Options", "structcopp_1_1solver_1_1topp2__ra_1_1_options.html", null ],
    [ "copp::Path", "classcopp_1_1_path.html", null ],
    [ "copp::PathDerivatives", "structcopp_1_1_path_derivatives.html", null ],
    [ "copp::solver::copp2_socp::Problem", "classcopp_1_1solver_1_1copp2__socp_1_1_problem.html", null ],
    [ "copp::solver::copp3_socp::Problem", "classcopp_1_1solver_1_1copp3__socp_1_1_problem.html", null ],
    [ "copp::solver::topp2_ra::Problem", "classcopp_1_1solver_1_1topp2__ra_1_1_problem.html", null ],
    [ "copp::solver::topp3::Problem", "classcopp_1_1solver_1_1topp3_1_1_problem.html", null ],
    [ "copp::Profile3rd", "structcopp_1_1_profile3rd.html", null ],
    [ "copp::Profile3rdRef", "structcopp_1_1_profile3rd_ref.html", null ],
    [ "copp::solver::topp2_ra::ReachSet", "structcopp_1_1solver_1_1topp2__ra_1_1_reach_set.html", null ],
    [ "copp::solver::copp2_socp::Result", "structcopp_1_1solver_1_1copp2__socp_1_1_result.html", null ],
    [ "copp::solver::topp3::Result", "structcopp_1_1solver_1_1topp3_1_1_result.html", null ],
    [ "copp::Robot", "classcopp_1_1_robot.html", null ],
    [ "std::runtime_error", null, [
      [ "copp::Error", "classcopp_1_1_error.html", null ]
    ] ],
    [ "copp::clarabel::Settings", "structcopp_1_1clarabel_1_1_settings.html", null ],
    [ "copp::Span&lt; T &gt;", "classcopp_1_1_span.html", null ],
    [ "copp::SplineConfig", "structcopp_1_1_spline_config.html", null ],
    [ "copp::solver::topp3::StationaryBounds", "structcopp_1_1solver_1_1topp3_1_1_stationary_bounds.html", null ],
    [ "copp::interpolation::TimeGridOptions", "structcopp_1_1interpolation_1_1_time_grid_options.html", null ],
    [ "copp::interpolation::TimeProfile", "structcopp_1_1interpolation_1_1_time_profile.html", null ],
    [ "ToyArmDynamics", "struct_toy_arm_dynamics.html", null ]
];